---
slug: kubernetes-fundamentals
filename: kubernetes-fundamentals
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2016
uuid: 74ea259c-dd83-4b9a-8bc2-99d04de57d79
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
